config/routes.rb
Rails.application.routes.draw do

  resources :first_categories

  resources :user_addresses

  resources :comments

  resources :customers

  resources :member_users

  resources :orders do
    collection do
      post :dispatch_goods
    end
  end

  resources :categories

  resources :goods do
    collection do
      post :set_display
      post :set_hot
    end
  end

  devise_for :users

  resources :users

  root 'users#index'

  namespace "monitor" do
    resources "logs"
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  mount Ckeditor::Engine => '/ckeditor'

  namespace :interface do
    resources :wechat, only: [:index]

    resources :payments do
      collection do
        post :pay
        post :user_pay
        post :notify
      end
    end

    resources :goods do
      collection do
        get :get_goods
        get :goods_details
        post :buy
        get :buy_success
      end
    end

    resources :customers do
      collection do
        get :user_info
      end
    end

    resources :orders do
      collection do
        get :get_all_orders
      end
    end

  end
end

app/models/member_user.rb
class MemberUser < ActiveRecord::Base
  has_many :comments
  has_many :user_addresses
  has_many :orders
  has_one :shop_cart
end

app/controllers/member_users_controller.rb
class MemberUsersController < ApplicationController
  before_action :set_member_user, only: [:show, :edit, :update, :destroy]

  def index
    @member_users = MemberUser.all.page(params[:page]).order("created_at desc")
  end

  #def show
  #end

  #def new
  #  @member_user = MemberUser.new
  #end

  #def edit
  #end

  #def create
  #  @member_user = MemberUser.new(member_user_params)
  #  @member_user.save

  #  redirect_to member_users_path
  #end

  #def update
  #  @member_user.update(member_user_params)

  #  redirect_to member_users_path
  #end

  def destroy
    @member_user.destroy

    redirect_to member_users_path
  end

  private
    def set_member_user
      @member_user = MemberUser.find(params[:id])
    end

    def member_user_params
      params.require(:member_user).permit(:email)
    end
end

app/views/member_users/_form.html.erb
<%= form_for(@customer) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :open_id %><br>
    <%= f.text_field :open_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/member_users/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/member_users/index.html.erb
<%= content_for :locbar do %>
  操作
  &raquo;
  pc顾客管理
<% end %>

<div class="page-header">
  <h1>pc顾客列表</h1>
</div>

<%= form_for Customer.new, :url => member_users_path, :html => {:method=>'get', :class => "form-horizontal" } do |f| %>
  <div class='form-inline'>
    <%= f.label '顾客邮箱:'%>
    <%= f.text_field :name, name: 'name', :class => 'form-control', style: "width: 250px", placeholder: '请输入邮箱(支持模糊查询)', value: params[:name] %>
    <%= f.submit "查询", :class => 'btn btn-primary'  %>
  </div>
<% end %>

<br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>邮箱</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @member_users.each do |member_user| %>
      <tr>
        <td><%= member_user.email %></td>
        <td>
          <%#= link_to "查看", member_user_path(member_user), :class => 'btn btn-default btn-xs' %>
          <%#= link_to "编辑", edit_member_user_path(member_user), :class => 'btn btn-primary btn-xs' %>
          <%= link_to "删除", member_user_path(member_user), :method => :delete,
                      :data => { :confirm => '确定删除吗?' }, :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="table-actions-bottom">
  <%= pagination @member_users %>
</div>

<%#= link_to "新建", new_member_user_path, :class => 'btn btn-primary' %>

app/views/member_users/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/member_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @customer.avatar %>
</p>

<p>
  <strong>Open:</strong>
  <%= @customer.open_id %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>