config/routes.rb
Rails.application.routes.draw do

  resources :first_categories

  resources :user_addresses

  resources :comments

  resources :customers

  resources :member_users

  resources :orders do
    collection do
      post :dispatch_goods
    end
  end

  resources :categories

  resources :goods do
    collection do
      post :set_display
      post :set_hot
    end
  end

  devise_for :users

  resources :users

  root 'users#index'

  namespace "monitor" do
    resources "logs"
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  mount Ckeditor::Engine => '/ckeditor'

  namespace :interface do
    resources :wechat, only: [:index]

    resources :payments do
      collection do
        post :pay
        post :user_pay
        post :notify
      end
    end

    resources :goods do
      collection do
        get :get_goods
        get :goods_details
        post :buy
        get :buy_success
      end
    end

    resources :customers do
      collection do
        get :user_info
      end
    end

    resources :orders do
      collection do
        get :get_all_orders
      end
    end

  end
end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :category
  has_many :goods_photos
  has_many :buy_goods
  has_many :comments
  has_many :shop_cart_goods

  def show_goods_first_image
    self.goods_photos.first.image_url
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy, :set_display, :set_hot]

  def index
    @goods = Good.all.page(params[:page]).order("created_at desc")
    @goods = @goods.where("name like ?", "%#{params[:name]}%") if params[:name].present?
  end

  def show
  end

  def new
    @good = Good.new
  end

  def edit
  end

  def create
    @good = Good.new(good_params)
    @good.save

    if params[:photos].present?
      Tool.upload_images(params[:photos][:image_url], @good.id, "good_id", GoodsPhoto)
    end
    flash[:success] = "新建成功"

    redirect_to goods_path
  end

  def update
    @good.update(good_params)

    if params[:photos].present?
      @good.goods_photos.destroy_all   #将原来的图片删掉
      Tool.upload_images(params[:photos][:image_url], @good.id, "good_id", GoodsPhoto)
    end
    flash[:success] = "编辑成功"

    redirect_to goods_path
  end

  def destroy
    @good.destroy
    flash[:success] = "删除成功"

    redirect_to goods_path
  end

  def set_display
    if @good.is_display
      @good.is_display = false
      @good.save
      redirect_to goods_path, notice: '下架成功'
    else
      @good.is_display = true
      @good.save
      redirect_to goods_path, notice: '上架成功'
    end
  end

  def set_hot
    if @good.is_hot
      @good.is_hot = false
      @good.save
      redirect_to goods_path, notice: '取消推荐成功'
    else
      @good.is_hot = true
      @good.save
      redirect_to goods_path, notice: '商品推荐成功'
    end
  end

  private
    def set_good
      @good = Good.find(params[:id])
    end

    def good_params
      params.require(:good).permit(:name, :advertisement, :inventory, :good_attribute, :description, :price, :original_price, :category_id)
    end
end

app/controllers/interface/goods_controller.rb
# -*- encoding : utf-8 -*-
class Interface::GoodsController < Interface::ApplicationController
  def get_goods
    goods = Good.all.order("created_at desc")

    render :json => {
      goods: goods.map { |good|
        {
          id: good.id,
          name: good.name,
          description: good.description,
          image_url: good.goods_photos.first.image_url,
          category_id: good.category_id
        }
      }
    }
  end

  def goods_details
    good = Good.find(params[:good_id])

    render :json => {
      good: {
        id: good.id,
        name: good.name,
        description: good.description,
        price: good.price.to_f,
        original_price: good.original_price.to_f,
        category_id: good.category_id
      },
      good_images: good.goods_photos.map { |photo|
         photo.image_url
      }
    }
  end

  def buy
    customer = Customer.find_by_open_id(params[:open_id])

    order = Order.new(
      :receiver_address => params[:mobile_user_address],
      :receiver_name => params[:mobile_user_name],
      :receiver_phone => params[:mobile_user_phone],
      :total_cost => params[:total_cost],
      :order_status => false,
      :guest_remarks => params[:guest_remarks],
      :customer_id => customer.id
    )
    if params[:good_id].present?
      Order.transaction do
        good = Good.find(params[:good_id])
        order.generate_order_id
        order.save
        Rails.logger.info("订单号======== #{order.order_id}")

        buy_good = BuyGood.new(
          :order_id => order.id,
          :good_id => params[:good_id],
          :quantity => params[:buy_count]
        )
        buy_good.save

        render json: {
          amount: order.total_cost,
          order_number: order.order_id,
          order_id: order.id
        }
      end
    elsif params[:goods].present?
      Rails.logger.info " goods ===== #{params[:goods].values} "
      #render json: {
      #   message: 'error'
      #} and return

      Order.transaction do
        order.generate_order_id
        order.save
        Rails.logger.info("订单号======== #{order.order_id}")

        params[:goods].values.each do |good|
          buy_good = BuyGood.new(
            :order_id => order.id,
            :good_id => good[:id],
            :quantity => good[:quantity]
          )
          buy_good.save
        end

        render json: {
          amount: order.total_cost,
          order_number: order.order_id,
          order_id: order.id
        }
      end
    end
  end

  def buy_success
    #order = Order.find_by_order_id(params[:order_id])
    order = Order.last

    render :json => {
      order:
        {
          id: order.id,
          receiver_name: order.receiver_name,
          receiver_address: order.receiver_address,
          receiver_phone: order.receiver_phone,
          total_cost: order.total_cost,
        }
    }
  end

end

app/views/goods/_form.html.erb
<%= form_for @good, :html => { :class => "form-horizontal good" } do |f| %>

  <div class="control-group">
    <%= f.label "商品名称", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "广告标语", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :advertisement, :class => 'form-control', style: "width: 600px;" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "商品属性", :class => 'control-label' %>
    <div class="controls">
      <%= f.cktext_area :good_attribute, style: "" %>
    </div>
  </div>

  <br/>

  <div class="control-group">
    <%= f.label "商品详情描述", :class => 'control-label' %>
    <div class="controls">
      <%= f.cktext_area :description,style: "width: 400px; height: 200px;" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "商品库存", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :inventory, :class => 'form-control' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "商品折后价", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "商品原价", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :original_price, :class => 'form-control' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label "图片", :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image_url, :class => 'form-control', :multiple => true, name: "photos[image_url][]" %>

      <% if @good.goods_photos.present? %>
        <% @good.goods_photos.each  do |photo| %>
          <%= image_tag photo.image_url, style: "width: 100px;" %>
        <% end %>
      <% else %>
        暂无图片
      <% end %>

    </div>
  </div>

  <div class="control-group">
    <%= f.label "商品分类", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name, @good.category_id), {:include_blank => "请选择分类"}, :class => 'form-control' %>
    </div>
  </div>

  <br/>

  <%= f.submit "确定", :class => 'btn btn-primary' %>
  <%= link_to "返回", goods_path, :class => 'btn btn-default'  %>

<% end %>

app/views/goods/edit.html.erb
<%= content_for :locbar do %>
  商品
  &raquo;
  编辑商品
<% end %>

<div class="page-header">
  <h1>编辑商品页</h1>
</div>

<%= render :partial => 'form' %>

app/views/goods/index.html.erb
<%= content_for :locbar do %>
  商品
  &raquo;
  商品管理
<% end %>

<div class="page-header">
  <h1>商品列表</h1>
</div>

<%= form_for Good.new, :url => goods_path, :html => {:method=>'get', :class => "form-horizontal" } do |f| %>
  <div class='form-inline'>
    <%= f.label '商品名称:'%>
    <%= f.text_field :name, name: 'name', :class => 'form-control', style: "width: 250px", placeholder: '请输入商品名称(支持模糊查询)', value: params[:name] %>
    <%= f.submit "查询", :class => 'btn btn-primary'  %>
  </div>

<% end %>

<br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>商品名称</th>
      <th>所属二级分类</th>
      <!--<th style="width: 400px;">商品描述</th>-->
      <th>商品折后价</th>
      <th>商品原价</th>
      <th>库存(件)</th>
      <th>图片</th>
      <th>上架时间</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.name %></td>
        <!--<td><%= raw good.good_attribute %></td>-->
        <td><%= good.category.name rescue '' %></td>
        <td><%= good.price %>元</td>
        <td><%= good.original_price %>元</td>
        <td><%= good.inventory %></td>
        <td><%= image_tag (good.goods_photos.first.try :image_url), style: "width: 100px;" %></td>
        <td><%= good.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td>
          <%= link_to "查看", good_path(good), :class => 'btn btn-default btn-xs' %>
          <%= link_to "编辑", edit_good_path(good), :class => 'btn btn-primary btn-xs' %>
          <%= link_to "删除", good_path(good), :method => :delete,
                      :data => { :confirm => '确定删除该商品吗?' }, :class => 'btn btn-xs btn-danger' %>
          <% if good.is_display %>
            <%= link_to "下架", set_display_goods_path(:id => good.id), method: "post", :class => 'btn btn-danger btn-xs' %>
          <% else %>
            <%= link_to "上架", set_display_goods_path(:id => good.id), method: "post", :class => 'btn btn-success btn-xs' %>
          <% end %>
          <% if good.is_hot %>
            <%= link_to "取消推荐", set_hot_goods_path(:id => good.id), method: "post", :class => 'btn btn-danger btn-xs' %>
          <% else %>
            <%= link_to "推荐商品", set_hot_goods_path(:id => good.id), method: "post", :class => 'btn btn-success btn-xs' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="table-actions-bottom">
  <%= pagination @goods %>
</div>

<%= link_to "新建", new_good_path, :class => 'btn btn-primary' %>

app/views/goods/new.html.erb
<%= content_for :locbar do %>
  商品
  &raquo;
  新建商品
<% end %>

<div class="page-header">
  <h1>新建商品页</h1>
</div>

<%= render :partial => 'form' %>

app/views/goods/show.html.erb
<%= content_for :locbar do %>
  商品
  &raquo;
  商品详情
<% end %>

<dl class="dl-horizontal">
  <dt><strong>商品名称:</strong></dt>
  <dd><%= @good.name %></dd>
  <dt><strong>广告标语:</strong></dt>
  <dd><%= @good.advertisement %></dd>
  <dt><strong>商品属性:</strong></dt>
  <dd><%= raw @good.good_attribute %></dd>
  <dt><strong>商品描述:</strong></dt>
  <dd><%= raw @good.description %></dd>
  <dt><strong>商品折后价:</strong></dt>
  <dd><%= @good.price %>元</dd>
  <dt><strong>商品原价:</strong></dt>
  <dd><%= @good.original_price %>元</dd>
  <dt><strong>库存:</strong></dt>
  <dd><%= @good.inventory %>件</dd>
  <dt><strong>图片:</strong></dt>
  <% @good.goods_photos.each do |photo| %>
    <dd><%= image_tag photo.image_url, style: "width: 200px;"%></dd>
  <% end %>
</dl>

<%= link_to "编辑", edit_good_path(@good), :class => 'btn btn-primary' %>
<%= link_to "返回", goods_path, :class => 'btn btn-default'  %>